name: Analyse
# on: pull_request
on:
  workflow_call:

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
          php_extensions: bcmath

      - name: install tools
        run: |
          mkdir --parents tools/phpstan tools/phpunit
          composer require phpstan/phpstan --working-dir=tools/phpstan --no-interaction  --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
          composer require phpunit/phpunit --working-dir=tools/phpunit --no-interaction  --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: analyse
        run: tools/phpstan/vendor/bin/phpstan --error-format=github --no-progress
