name: coding standards
on: [push, pull_request]
jobs:
  check-cs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
          php_extensions: zip gd

      - name: Check formatting
        # run: ./vendor/bin/ecs check
        # run: ./vendor/bin/ecs check $(echo $(git diff --name-only $COMMIT_RANGE))
        run: echo $COMMIT_RANGE
        env:
          COMMIT_RANGE: "${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}"
