name: coding standards
on: [pull_request]
# on: [push, pull_request] # runs twice
jobs:
  check-cs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
          php_extensions: zip gd

      - name: check
        # --diff-filter=d ignore deleted files
        run: composer check-cs -- $(echo $(git diff --diff-filter=d --name-only "$COMMIT_RANGE"))
        env:
          COMMIT_RANGE: "${{ github.event.before }}...${{ github.event.after }}"

      - name: comment on failure
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const body = `❌ Our coding standards were not met.
                          please run 
                          \```shell
                           composer fix-cs
                          \```
                          \n see ${url}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
