name: coding standards
on: [pull_request]
# on: [push, pull_request] # runs twice
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
          php_extensions: zip gd bcmath

      - name: install tools
        run: composer install-tools

#      - name: check
#        # --diff-filter=d ignore deleted files
#        # run: composer cs -- $(echo $(git diff --diff-filter=d --name-only "$COMMIT_RANGE"))
#        run: composer cs
#        env:
#          COMMIT_RANGE: "${{ github.event.before }}...${{ github.event.after }}"

      - name: start server
        # run: php -S localhost:4444 -t public &
        run: composer start-server &

      - name: run tools
        run: composer ci
        env:
          XDEBUG_MODE: coverage
          ECS_OUTPUT_FORMAT: checkstyle
          PHPSTAN_OUTPUT_FORMAT: github

      - name: comment on failure
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const body = '❌ Our coding standards were not met.\nplease run\n```shell\ncomposer fix-cs\n```\nsee ' + url;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
