name: Test
on: pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
          php_extensions: bcmath

      - name: install phpunit
        run:
          mkdir --parents tools/phpunit
          composer require phpunit/phpunit --working-dir=tools/phpunit --no-interaction  --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

#      - name: Composer dependencies
#        run: composer require phpunit/phpunit --dev --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: start server
        run: composer start-server &
      - name: configure matchers
        uses: mheap/phpunit-matcher-action@v1
      - name: run tests
        run: tools/phpunit/vendor/bin/phpunit --teamcity tests
        env:
          XDEBUG_MODE: coverage
