name: Test
on: [pull_request]
# on: [push, pull_request] # runs twice
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
          php_extensions: zip gd bcmath

      - name: install tools
        run: composer install-tools

      - name: add printer
        run: composer require --dev mheap/phpunit-github-actions-printer

      - name: start server
        run: composer start-server &

      - name: run tests
        run: tools/phpunit/vendor/bin/phpunit --printer mheap\\GithubActionsReporter\\Printer tests
        env:
          XDEBUG_MODE: coverage
